**<font color='orange' size='+2'>CHURN PREDICTION OF A BANK USING ARTIFICIAL NEURAL NETWORKS</font>**

# Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Importing Dataset

In [2]:
dset = pd.read_csv("Churn_Data.csv")
X = dset.iloc[:, 3:-1].values
y = dset.iloc[:, -1].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding Categorical Data

### Onehot encoding 'Geography' column

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
print(X)
# Dummy variables are moved to first column

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Label encoding 'Gender' column

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 4] = le.fit_transform(X[:, 4])

In [8]:
print(X[:, 4])

[0 0 0 ... 0 1 0]


In [9]:
print(X[0])

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


# Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [11]:
print(X_train)

[[1.0 0.0 0.0 ... 1 1 179093.26]
 [0.0 1.0 0.0 ... 1 1 195978.86]
 [0.0 0.0 1.0 ... 1 0 85891.02]
 ...
 [1.0 0.0 0.0 ... 0 0 92220.12]
 [1.0 0.0 0.0 ... 1 0 97508.04]
 [0.0 1.0 0.0 ... 1 1 53581.14]]


In [12]:
print(X_test)

[[0.0 1.0 0.0 ... 0 0 41788.37]
 [1.0 0.0 0.0 ... 1 1 146379.3]
 [0.0 0.0 1.0 ... 1 0 58561.31]
 ...
 [1.0 0.0 0.0 ... 1 0 33373.26]
 [1.0 0.0 0.0 ... 1 0 76755.99]
 [0.0 1.0 0.0 ... 1 1 107674.3]]


# Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   1.36766974]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   1.6612541 ]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.25280688]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ... -1.54035103 -1.02583358
  -0.1427649 ]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.05082558]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
  -0.81456811]]


In [15]:
print(X_test)

[[-0.99850112  1.72572313 -0.57638802 ... -1.54035103 -1.02583358
  -1.01960511]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   0.79888291]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.72797953]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -1.16591585]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.41163463]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   0.12593183]]


# Making the Artificial Neural Network

In [16]:
# Initialisation
ann = tf.keras.models.Sequential()

# Adding Input and First Hidden Layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding Second Hidden Layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding Output Layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Training the Aritificial Neural Network

In [17]:
# Compiling the ANN
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN
ann.fit(X_train, y_train, batch_size = 32, epochs = 80)

Epoch 1/80
250/250 [==============================] - 4s 7ms/step - loss: 0.5688 - accuracy: 0.7412
Epoch 2/80
250/250 [==============================] - 2s 9ms/step - loss: 0.4729 - accuracy: 0.7960
Epoch 3/80
250/250 [==============================] - 2s 7ms/step - loss: 0.4524 - accuracy: 0.7996
Epoch 4/80
250/250 [==============================] - 1s 5ms/step - loss: 0.4415 - accuracy: 0.8074
Epoch 5/80
250/250 [==============================] - 1s 5ms/step - loss: 0.4335 - accuracy: 0.8109
Epoch 6/80
250/250 [==============================] - 1s 6ms/step - loss: 0.4259 - accuracy: 0.8134
Epoch 7/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4174 - accuracy: 0.8171
Epoch 8/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4067 - accuracy: 0.8253
Epoch 9/80
250/250 [==============================] - 0s 2ms/step - loss: 0.3941 - accuracy: 0.8319
Epoch 10/80
250/250 [==============================] - 0s 2ms/step - loss: 0.3813 - accuracy: 0.8397

# Making Predictions

In [18]:
# Predicting Test Data
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 1ms/step


In [19]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]


# Evaluation Using COnfusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score

cmat = confusion_matrix(y_test, y_pred)
print(cmat)
accuracy_score(y_test, y_pred)

[[1543   64]
 [ 208  185]]


0.864